version: "3.2"

services:
    nginx:
        build: ./nginx/
        ports:
            - ${HOST_HTTP_PORT}:80        
        volumes:
            - type: bind
              source: ${PROJECT_ROOT}
              target: /var/www/html
        networks:
            - server
        depends_on:
            - php
            
    php:
        build: ./php/        
        expose:
            - 9000
        volumes:
            - type: bind
              source: ${PROJECT_ROOT}
              target: /var/www/html
        networks:
            - database
            - server
        depends_on:
            - mysql             
        
    mysql:
        build: ./mysql/
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - database        
        ports: 
            - ${HOST_MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"            
        command: --default-authentication-plugin=mysql_native_password            
        restart: always
        
volumes:
    mysql_data:
        external: true
    
networks:
    database:
    server: